### ISSUE TITLE
updated css and index, im not sure if i updated it correctly. But i connected your files with my index file

### ISSUE THREAD

**Issue by fernrey** [Oleksii-Kravtsov/Assignment-1#10]

**Comment by Oleksii-Kravtsov** [comment]
let me move the index.html back to the root folder. Cause I remember in the prework tutorial it said that index.html is always in the root folder.

**Comment by fernrey** [comment]
oh get rid of the index folder outside of the folder, i remember that was just us testing . The original one is in the folder :)
