### ISSUE TITLE
I see a lot of options but none of them work

### ISSUE THREAD

**Issue by Oleksii-Kravtsov** [Oleksii-Kravtsov/Assignment-1#11]
You added a lot of pseudo pages, and one of them is mine. A person checking this may not even think that one of them works and actually think that we only have 1 page working. Would it be possible that you remove all the other pseudo pages and keep the one that links to pineapple pizza?

**Comment by fernrey** [comment]
OH YEA. sorry I was only going to have 3 which would be your page, the about us. and contact us. I for sure will update it.

**Comment by fernrey** [comment]
i add a little more, i moved the index file to the html folder, could you make it so that it opens the files from the index folder? i got rid of the extra pseudo pages.

**Comment by Oleksii-Kravtsov** [comment]
hey, I previously moved the index to the root folder away from the html folder because in the prework it said that the index should always be in the root folder.
